---

 - name: Practica ansible
   hosts: "webservers"
  # remote_user: vagrant

   become: true
   become_user: root
   roles:
     - { role: geerlingguy.apache }
     - { role: geerlingguy.mysql }
     - { role: carlos.copyfiles }



